--- 
title: "Introdução ao pacote D3plusR"
author: "Paulo Felipe Alencar de Oliveira"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::html_book:
    theme: united
    includes:
      in_header: header.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Tutorial do pacote D3plusR."
---



# Visão Geral

## Sobre o D3plus e o D3plusR

O pacote `D3plusR` é um widget criado a partir do _framework_ fornecido pelo pacote `htmlwidgets`. De forma resumida, esse pacote fornece uma estrutura em que se torna possível a incorporação de bibliotecas de visualizações desenvolvidas em javascript em análises desenvolvidas com o R. 

Como o nome do pacote indica, esse pacote usa a biblioteca [`D3plus`](https://d3plus.org/) que, por sua vez, é construída em cima da biblioteca mais genérica [`D3`](https://d3js.org/). A criação de visualizações diretamente com D3 pode ser um pouco desafiadora no início. Dessa forma, os autores do pacote `D3plus` criaram um conjunto de visualizações pré-definidas em que é possível criar, de maneira simples, visualizações efetivas e com uma qualidade final consideravelmente alta.

## Instalando o pacote

O pacote ainda não possui uma versão 1.0. A sua versão de desenvolvimento está disponível no [github](https://github.com/paulofelipe/D3plusR). Para instalar, é necessário usar o pacote `devtools`:

```{r, eval=FALSE}
devtools::install_github('paulofelipe/D3plusR')
```

## Pacotes adicionais necessário para o tutorial

Nos exemplos desse livro, os seguintes pacotes também serão necessários:

* dplyr
* jsonlite
* readxl
* tidyr

## Opções das funções

Na documentação do pacote não estão listadas todas as opções disponíveis para a criação de visualizações. Sugere-se que o usuário utiliza a página disponibilizada pelos autores do `D3plus`. 

 [**Opções da biblioteca**](https://github.com/alexandersimoes/d3plus/wiki/Visualizations)
 
 Com as explicações dos próximos capítulos e os exemplos, ficará mais intuitivo de como usar as opções listadas no link acima.
 
## Dados utilizados nos exeplos

Os dados utilizados nos exemplos estão disponíveis [neste link]()

<!-- add after bootstrap.min.css -->
<link rel="stylesheet" href="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.4.1/dist/bootstrap-toc.min.css">
<!-- add after bootstrap.min.js -->
<script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v0.4.1/dist/bootstrap-toc.min.js"></script>
